/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.NhanVienController;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.BaiDang;
import model.ChiTietPhieuMua;
import model.PhieuMua;
import model.SanPham;
import model.TaiKhoan;

/**
 *
 * @author Trong
 */
public class NhanVienForm extends javax.swing.JFrame {

    NhanVienController nhanVienController;

    /**
     * Creates new form ThuKhoForm
     */
    public NhanVienForm() {
        initComponents();
        this.setResizable(false);
        nhanVienController = new NhanVienController();
        loadDonHang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneDangBai = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblDonHang = new javax.swing.JTable();
        btnHuy = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfMaKH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfTenKH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfSoDT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfDiaChi = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTieuDe = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        tfTieuDe = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taNoiDung = new javax.swing.JTextArea();
        btnThem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnThoat1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giao diện của nhân viên");

        jTabbedPaneDangBai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneDangBaiMouseClicked(evt);
            }
        });

        jLabel20.setText("Xác nhận đơn hàng");

        tblDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã đơn hàng", "Trạng thái đơn hàng", "Địa chỉ giao hàng", "Ngày đặt hàng"
            }
        ));
        tblDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDonHangMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tblDonHang);

        btnHuy.setText("Hủy đơn hàng");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnXacNhan.setText("Xác nhận đơn hàng");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Đơn vị", "Đơn giá", "Số lượng"
            }
        ));
        jScrollPane10.setViewportView(tblSanPham);

        jLabel1.setText("Tổng thanh toán");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTongTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel5.setText("Thông tin khách hàng");

        jLabel6.setText("Mã khách hàng");

        tfMaKH.setEditable(false);

        jLabel7.setText("Tên khách hàng");

        tfTenKH.setEditable(false);

        jLabel8.setText("Số điện thoại");

        tfSoDT.setEditable(false);

        jLabel9.setText("Địa chỉ");

        tfDiaChi.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(136, 136, 136))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap())
        );

        btnThoat.setText("Thoát");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(343, 343, 343))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy)
                    .addComponent(btnXacNhan)
                    .addComponent(btnThoat))
                .addContainerGap())
        );

        jTabbedPaneDangBai.addTab("Xác nhận đơn hàng", jPanel7);

        jLabel21.setText("Quản lý bài đăng");

        listTieuDe.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0)), "Tiêu đề bài đăng"));
        listTieuDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listTieuDeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listTieuDe);

        jLabel2.setText("Tiêu đề");

        jLabel3.setText("Nội dung");

        taNoiDung.setColumns(20);
        taNoiDung.setRows(5);
        jScrollPane1.setViewportView(taNoiDung);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel4.setText("Đính kèm file");

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnThoat1.setText("Thoát");
        btnThoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(jLabel21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField2))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(39, 39, 39)
                                        .addComponent(tfTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(btnThem)
                                .addGap(46, 46, 46)
                                .addComponent(btnSua)
                                .addGap(55, 55, 55)
                                .addComponent(btnXoa)
                                .addGap(50, 50, 50)
                                .addComponent(btnReset)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                                .addComponent(btnThoat1)))))
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTieuDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua)
                            .addComponent(btnXoa)
                            .addComponent(btnReset)
                            .addComponent(btnThoat1))
                        .addGap(23, 23, 23))))
        );

        jTabbedPaneDangBai.addTab("Quản lý bài đăng", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneDangBai)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneDangBai, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * load đơn hàng lên bảng khi mới khởi động
     */
    private void loadDonHang() {
        ArrayList<PhieuMua> listPhieuMua = nhanVienController.getDonHang();
        DefaultTableModel model = (DefaultTableModel) tblDonHang.getModel();
        for (int i = 0; i < listPhieuMua.size(); i++) {
            Object[] rowData = {listPhieuMua.get(i).getMaPhieu(), listPhieuMua.get(i).getTrangThai(), listPhieuMua.get(i).getDiaChiGiao(), listPhieuMua.get(i).getNgayDatHang()};
            model.addRow(rowData);
        }
    }


    private void tblDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDonHangMouseClicked
        DefaultTableModel model = (DefaultTableModel) tblDonHang.getModel();
        String maPhieuMua = model.getValueAt(tblDonHang.getSelectedRow(), 0).toString();
        ArrayList<ChiTietPhieuMua> listChiTiet = nhanVienController.getchiTietDonHang(maPhieuMua);
        DefaultTableModel modelSP = (DefaultTableModel) tblSanPham.getModel();
        for (int i = 0; i < listChiTiet.size(); i++) {
            int maSP = listChiTiet.get(i).getMaSanPham();
            int soLuong = listChiTiet.get(i).getSoLuong();
            SanPham sp = nhanVienController.getSanPhamMua(maSP);
            if (sp == null) {
                JOptionPane.showMessageDialog(null, "Không có sản phẩm !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            String tenSP = sp.getTenSP();
            String donVi = sp.getDonVi();
            int gia = sp.getGia();
            Object[] rowData = {maSP, tenSP, donVi, gia, soLuong};
            modelSP.addRow(rowData);
        }
        // tính tổng tiền thanh toán
        int tongTien = 0;
        for (int i = 0; i < tblSanPham.getRowCount(); i++) {
            tongTien += Integer.parseInt(modelSP.getValueAt(i, 3).toString()) * Integer.parseInt(modelSP.getValueAt(i, 4).toString());
        }
        lblTongTien.setText(tongTien + " " + modelSP.getValueAt(0, 2));

        TaiKhoan taiKhoan = nhanVienController.getTTTaiKhoan(maPhieuMua);
        if (taiKhoan == null) {
            JOptionPane.showMessageDialog(this, "Tài khoản không tồn tại !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
        tfMaKH.setText(String.valueOf(taiKhoan.getMaTK()));
        tfTenKH.setText(taiKhoan.getHoTen());
        tfSoDT.setText(taiKhoan.getSoDT());
        tfDiaChi.setText(taiKhoan.getDiaChi());
    }//GEN-LAST:event_tblDonHangMouseClicked

    private void clearDonHang() {
        DefaultTableModel modelSP = (DefaultTableModel) tblSanPham.getModel();
        modelSP.setRowCount(0);
        lblTongTien.setText("");
        tfDiaChi.setText("");
        tfMaKH.setText("");
        tfSoDT.setText("");
        tfTenKH.setText("");
    }
    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        int ok = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xác nhận không ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            DefaultTableModel model = (DefaultTableModel) tblDonHang.getModel();
            String maPhieuMua = model.getValueAt(tblDonHang.getSelectedRow(), 0).toString();
            if (nhanVienController.xacNhanDonHang(maPhieuMua)) {
                JOptionPane.showMessageDialog(this, "Xác nhận thành công !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                model.removeRow(tblDonHang.getSelectedRow());
                clearDonHang();
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật vào cơ sở dữ liệu !", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        int ok = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn hủy đơn hàng không ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            DefaultTableModel model = (DefaultTableModel) tblDonHang.getModel();
            String maPhieuMua = model.getValueAt(tblDonHang.getSelectedRow(), 0).toString();
            ArrayList<String> listMaSP = new ArrayList();
            DefaultTableModel modelSP = (DefaultTableModel) tblSanPham.getModel();
            for (int i = 0; i < tblSanPham.getRowCount(); i++) {
                String maSP = model.getValueAt(i, 0).toString();
                listMaSP.add(maSP);
            }
            if (nhanVienController.huyDonHang(maPhieuMua, listMaSP)) {
                JOptionPane.showMessageDialog(this, "Hủy đơn hàng thành công !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                model.removeRow(tblDonHang.getSelectedRow());
                clearDonHang();
            } else {
                JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật vào cơ sở dữ liệu !", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnHuyActionPerformed

    /**
     * giao diện đăng bài
     */
    private ArrayList<BaiDang> list;

    private void loadBaiDang() {
        list = nhanVienController.getBaiDang();
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < list.size(); i++) {
            model.addElement(list.get(i).getTieuDe());
        }
        listTieuDe.setModel(model);
    }
    private void jTabbedPaneDangBaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneDangBaiMouseClicked
        loadBaiDang();
    }//GEN-LAST:event_jTabbedPaneDangBaiMouseClicked

    private String findNoiDung(String tieuDe, ArrayList<BaiDang> list) {
        for (int i = 0; i < list.size(); i++) {
            if (tieuDe.equals(list.get(i).getTieuDe())) {
                return list.get(i).getNoiDung();
            }
        }
        return null;
    }

    private void listTieuDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listTieuDeMouseClicked
        String tieuDe = listTieuDe.getSelectedValue();
        String noiDung = findNoiDung(tieuDe, list);
        tfTieuDe.setText(tieuDe);
        taNoiDung.setText(noiDung);
    }//GEN-LAST:event_listTieuDeMouseClicked

    private boolean checkEmpty() {
        if (tfTieuDe.getText().isEmpty() || taNoiDung.getText().isEmpty()) {
            return true;
        }
        return false;
    }

    private boolean checkTieuDe(String tieuDe, ArrayList<BaiDang> list) {
        for (int i = 0; i < list.size(); i++) {
            if (tieuDe.equals(list.get(i).getTieuDe())) {
                return true;
            }
        }
        return false;
    }

    private void clearBaiDang() {
        tfTieuDe.setText("");
        taNoiDung.setText("");
    }

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        int ok = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn thêm không ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            if (checkEmpty()) {
                JOptionPane.showMessageDialog(this, "Còn thiếu thông tin !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                String tieuDe = tfTieuDe.getText();
                if (checkTieuDe(tieuDe, list)) {
                    JOptionPane.showMessageDialog(this, "Trùng tiêu đề !\nVui lòng nhập tiêu đề khác !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    String noiDung = taNoiDung.getText();
                    BaiDang baiDang = new BaiDang(tieuDe, noiDung);
                    if (nhanVienController.themBaiDang(baiDang)) {
                        JOptionPane.showMessageDialog(this, "Đăng bài thành công !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                        loadBaiDang();
                        clearBaiDang();
                    } else {
                        JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật vào cơ sở dữ liệu !", "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed


    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int ok = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn sửa không ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            if (listTieuDe.isSelectionEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn cần chọn một bài đăng để sửa !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (checkEmpty()) {
                    JOptionPane.showMessageDialog(this, "Còn thiếu thông tin !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    String tieuDe = tfTieuDe.getText();
                    if (checkTieuDe(tieuDe, list)) {
                        JOptionPane.showMessageDialog(this, "Trùng tiêu đề !\nVui lòng nhập tiêu đề khác !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        String noiDung = taNoiDung.getText();
                        int maBaiDang = list.get(listTieuDe.getSelectedIndex()).getMaBaiDang();
                        BaiDang baiDang = new BaiDang(maBaiDang, tieuDe, noiDung);
                        if (nhanVienController.suaBaiDang(baiDang)) {
                            JOptionPane.showMessageDialog(this, "Sửa bài đăng thành công !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                            loadBaiDang();
                            clearBaiDang();
                        } else {
                            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật vào cơ sở dữ liệu !", "Lỗi", JOptionPane.ERROR_MESSAGE);
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int ok = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xác nhận không ?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            if (listTieuDe.isSelectionEmpty()) {
                JOptionPane.showMessageDialog(this, "Bạn cần chọn một bài đăng để xóa !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            } else {
                int maBaiDang = list.get(listTieuDe.getSelectedIndex()).getMaBaiDang();
                if (nhanVienController.xoaBaiDang(maBaiDang)) {
                    JOptionPane.showMessageDialog(this, "Xóa bài đăng thành công !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    loadBaiDang();
                    clearBaiDang();
                } else {
                    JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật vào cơ sở dữ liệu !", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        clearBaiDang();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnThoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnThoat1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhanVienForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThoat1;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPaneDangBai;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JList<String> listTieuDe;
    private javax.swing.JTextArea taNoiDung;
    private javax.swing.JTable tblDonHang;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField tfDiaChi;
    private javax.swing.JTextField tfMaKH;
    private javax.swing.JTextField tfSoDT;
    private javax.swing.JTextField tfTenKH;
    private javax.swing.JTextField tfTieuDe;
    // End of variables declaration//GEN-END:variables
}
